# Java Gradle CircleCI 2.0 configuration file
# https://circleci.com/docs/2.0/sample-config/
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:

    working_directory: ~/RestaurantScores

    docker:
      - image: circleci/openjdk:8-jdk


    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - RestaurantScores-{{ checksum "build.gradle" }}

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: RestaurantScores-{{ checksum "build.gradle" }}

      - run: gradle test

      - store_artifacts:
          path: target/RestaurantScores-0.0.1-SNAPSHOT.jar

