scheduler: java $JAVA_OPTS -cp build/classes:build/dependency/* com.janeullah.healthinspectionrecords.RestaurantScoresTaskApplication
worker: java $JAVA_OPTS -cp build/classes:build/dependency/* com.janeullah.healthinspectionrecords.workers.WorkerMain
