# Use postgres/example user/password credentials
version: '3.1'

networks:
  restaurantscores-network:

services:

  #https://hub.docker.com/_/postgres/
  restaurantscores-db:
    image: postgres:latest
    container_name: restaurantscores-db
    env_file:
    - ../../Docker/restaurantscores/environmentvariables-db.env
    ports:
    - "5433:5432"
    expose:
    - "5432" # signifies intent to expose the port for inter-docker container comms
    networks:
    - restaurantscores-network

  restaurantscores-server:
    image: restaurantscores-server:beta
    container_name: restaurantscores-server
    ports:
    - "8080:8080"
    - "8000:8000"
    depends_on:
    - restaurantscores-db
    links:
    - restaurantscores-db
    expose:
    - "8080"
    - "8000"
    volumes:
    - ../../Docker/restaurantscores/logs/:/usr/local/tomcat/logs
    - ../../Docker/restaurantscores/downloads/webpages:/usr/local/tomcat/downloads/webpages
    env_file:
    - ../../Docker/restaurantscores/environmentvariables-server.env
    environment:
    - CATALINA_HOME=/usr/local/tomcat
    - SPRING_PROFILES_ACTIVE=postgresql
    networks:
    - restaurantscores-network
