apiVersion: v1
kind: Service
metadata:
  labels:
    app: restaurantscores
  name: restaurantscores
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: restaurantscores
